inherit_from: .rubocop_todo.yml
Metrics/AbcSize:
    Max: 99

Metrics/BlockLength:
    Max: 250

Metrics/MethodLength:
    Max: 15

Metrics/ParameterLists:
    Max: 7

Metrics/LineLength:
    Max: 200
